name = "gimble-chat-broker"
main = "worker.js"
compatibility_date = "2025-03-01"
workers_dev = true

[[kv_namespaces]]
binding = "SESSIONS"
id = "29aa2e07713346598419cd601e323945"

[[durable_objects.bindings]]
name = "SESSION_BROKER"
class_name = "SessionBroker"

[[migrations]]
tag = "v2-session-broker-do"
new_sqlite_classes = ["SessionBroker"]
